### ISSUE TITLE
Code style compliance

### ISSUE THREAD

**Issue by strilov** [DUNE-DAQ/timing#5]
Several points to fix:

- couts
- globals
- camel case in cpp files
- use of uint32, etc. in some places

**Comment by jcfreeman2** [comment]
@strilov Couple of other quick compliance points besides the ones listed above:
* `core_wrapper.cpp` and `FIBIONode.cpp` are missing our standard copyright
* All thrown exceptions are swallowed without a message in the call to `getNode<I2CMasterNode>(m_uid_i2c_bus).get_slave("AX3_Switch").write_i2c(0x01, 0x7f);` in `FIBIONode.cpp`
* It seems like in a lot of places unsigned integers are justified because they represent a bit pattern, not a number which one would use for calculations. In this case, adding ` // NOLINT` to the line will get the linter to quiet down

**Comment by strilov** [comment]
resolved
